### ISSUE TITLE
Getting 403 return code when initializing SchemaVersion class

### ISSUE THREAD

**Issue by odieduck** [fge/json-schema-core#23]
Stacktrace:
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.github.fge.jsonschema.SchemaVersion.<init>(SchemaVersion.java:66)
	at com.github.fge.jsonschema.SchemaVersion.<clinit>(SchemaVersion.java:45)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://json-schema.org/draft-04/schema#
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at java.net.URL.openStream(URL.java:1041)
	at com.github.fge.jackson.JsonLoader.fromURL(JsonLoader.java:117)
	at com.github.fge.jsonschema.SchemaVersion.<init>(SchemaVersion.java:64)

It seems sometimes the HTTP request to get the JSON schema will fail due to firewall settings.

If we change the code to this we can avoid this issue:

location = URI.create(uri);
URL url = new URL(uri);
HttpURLConnection conn = (HttpURLConnection) url.openConnection();
conn.addRequestProperty("User-Agent","Test");
schema = JsonLoader.fromReader(new InputStreamReader(conn.getInputStream()));

**Comment by daveclayton** [comment]
Hi @odieduck 

The current version in master appears to be loading from the resource in the classpath.

Is this still an issue?

**Comment by BenShaw** [comment]
Any information on this ? i seem to be getting the same issue.

**Comment by odieduck** [comment]
It's no longer a issue for us. We overwrite this class and load the scheme from class path. It's painful for us to upgrade dependency versions.

The new version has changed this, therefore, I'm ok to close this issue.

Thanks for looking into it!
